function [noise] = noise(rnd,parts)

if rnd<=parts(1)
    noise=1;

    elseif rnd<=sum(parts(1:2))
    noise=2;
    elseif rnd<=sum(parts(1:3))
    noise=3;
    elseif rnd<=sum(parts(1:4))
    noise=4;
   elseif rnd<=sum(parts(1:5))
    noise=5;
    elseif rnd<=sum(parts(1:6))
    noise=6;
    elseif rnd<=sum(parts(1:7))
    noise=7;
    elseif rnd<=sum(parts(1:8))
    noise=8;
    elseif rnd<=sum(parts(1:9))
    noise=9;
    elseif rnd<=sum(parts(1:10))
    noise=10;
    elseif rnd<=sum(parts(1:11))
    noise=11;
    elseif rnd<=sum(parts(1:12))
    noise=12;
    elseif rnd<=sum(parts(1:13))
    noise=13;
    elseif rnd<=sum(parts(1:14))
    noise=14;
    elseif rnd<=sum(parts(1:15))
    noise=15;
    elseif rnd<=sum(parts(1:16))
    noise=16;
    elseif rnd<=sum(parts(1:17))
    noise=17;
    elseif rnd<=sum(parts(1:18))
    noise=18;
    elseif rnd<=sum(parts(1:19))
    noise=19;
    elseif rnd<=sum(parts(1:20))
    noise=20;
    elseif rnd<=sum(parts(1:21))
    noise=21;
    elseif rnd<=sum(parts(1:22))
    noise=22;
    elseif rnd<=sum(parts(1:23))
    noise=23;
    elseif rnd<=sum(parts(1:24))
    noise=24;
    elseif rnd<=sum(parts(1:25))
    noise=25;
    elseif rnd<=sum(parts(1:26))
    noise=26;
    elseif rnd<=sum(parts(1:27))
    noise=27;
    elseif rnd<=sum(parts(1:28))
    noise=28;
    elseif rnd<=sum(parts(1:29))
    noise=29;
    elseif rnd<=sum(parts(1:30))
    noise=30;
    elseif rnd<=sum(parts(1:31))
    noise=31;
    elseif rnd<=sum(parts(1:32))
    noise=32;
    elseif rnd<=sum(parts(1:33))
    noise=33;
    elseif rnd<=sum(parts(1:34))
    noise=34;
    
end
end